# Generated by Django 4.2 on 2023-04-27 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_user_post_author_alter_comment_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="author",
            new_name="author_id",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="post",
            new_name="post_id",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="author",
            new_name="author_id",
        ),
    ]
